# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_clecked', models.BooleanField()),
                ('hostname', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('stat', models.IntegerField(choices=[(1, '在线'), (0, '下线')])),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
