# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160504_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostprofile',
            old_name='be_clecked',
            new_name='be_checked',
        ),
    ]
